### PR TITLE
Use DeclarativeVersion API

### PR DESCRIPTION
**Pull request by dralley**

### CODE REVIEW

**Comment by bmbouter** [comment]
When testing against bafb, after the resolution of the fedorapeople fixture data issue I'm getting an error of `pulp_python/tests/functional/api/test_crud_content_unit.py::ContentUnitTestCase`. It has these failures:

```
pulp_python/tests/functional/api/test_crd_publications.py::PublicationsTestCase::test_01_create_publication PASSED                                                   [  3%]
pulp_python/tests/functional/api/test_crd_publications.py::PublicationsTestCase::test_02_read_publication PASSED                                                     [  6%]
pulp_python/tests/functional/api/test_crd_publications.py::PublicationsTestCase::test_02_read_publications PASSED                                                    [  9%]
pulp_python/tests/functional/api/test_crd_publications.py::PublicationsTestCase::test_03_read_publications PASSED                                                    [ 12%]
pulp_python/tests/functional/api/test_crd_publications.py::PublicationsTestCase::test_04_read_publications PASSED                                                    [ 15%]
pulp_python/tests/functional/api/test_crd_publications.py::PublicationsTestCase::test_05_read_publications PASSED                                                    [ 18%]
pulp_python/tests/functional/api/test_crd_publications.py::PublicationsTestCase::test_06_delete PASSED                                                               [ 21%]
pulp_python/tests/functional/api/test_crud_content_unit.py::ContentUnitTestCase::test_01_create_content_unit ERROR                                                   [ 24%]
pulp_python/tests/functional/api/test_crud_content_unit.py::ContentUnitTestCase::test_02_read_content_unit ERROR                                                     [ 27%]
pulp_python/tests/functional/api/test_crud_content_unit.py::ContentUnitTestCase::test_02_read_content_units ERROR                                                    [ 30%]
pulp_python/tests/functional/api/test_crud_content_unit.py::ContentUnitTestCase::test_03_fully_update ERROR                                                          [ 33%]
pulp_python/tests/functional/api/test_crud_content_unit.py::ContentUnitTestCase::test_03_partially_update ERROR                                                      [ 36%]
pulp_python/tests/functional/api/test_crud_content_unit.py::DeleteContentUnitRepoVersionTestCase::test_all PASSED                                                    [ 39%]
pulp_python/tests/functional/api/test_crud_publishers.py::CRUDPublishersTestCase::test_01_create_publisher PASSED                                                    [ 42%]
pulp_python/tests/functional/api/test_crud_publishers.py::CRUDPublishersTestCase::test_02_create_same_name PASSED                                                    [ 45%]
pulp_python/tests/functional/api/test_crud_publishers.py::CRUDPublishersTestCase::test_02_read_publisher PASSED                                                      [ 48%]
pulp_python/tests/functional/api/test_crud_publishers.py::CRUDPublishersTestCase::test_02_read_publishers PASSED                                                     [ 51%]
pulp_python/tests/functional/api/test_crud_publishers.py::CRUDPublishersTestCase::test_03_partially_update PASSED                                                    [ 54%]
pulp_python/tests/functional/api/test_crud_publishers.py::CRUDPublishersTestCase::test_04_fully_update PASSED                                                        [ 57%]
pulp_python/tests/functional/api/test_crud_publishers.py::CRUDPublishersTestCase::test_05_delete PASSED                                                              [ 60%]
pulp_python/tests/functional/api/test_crud_remotes.py::CRUDRemotesTestCase::test_01_create_remote PASSED                                                             [ 63%]
pulp_python/tests/functional/api/test_crud_remotes.py::CRUDRemotesTestCase::test_02_create_same_name PASSED                                                          [ 66%]
pulp_python/tests/functional/api/test_crud_remotes.py::CRUDRemotesTestCase::test_02_read_remote PASSED                                                               [ 69%]
pulp_python/tests/functional/api/test_crud_remotes.py::CRUDRemotesTestCase::test_02_read_remotes PASSED                                                              [ 72%]
pulp_python/tests/functional/api/test_crud_remotes.py::CRUDRemotesTestCase::test_03_partially_update PASSED                                                          [ 75%]
pulp_python/tests/functional/api/test_crud_remotes.py::CRUDRemotesTestCase::test_04_fully_update PASSED                                                              [ 78%]
pulp_python/tests/functional/api/test_crud_remotes.py::CRUDRemotesTestCase::test_05_delete PASSED                                                                    [ 81%]
pulp_python/tests/functional/api/test_crud_remotes.py::CreateRemoteNoURLTestCase::test_all PASSED                                                                    [ 84%]
pulp_python/tests/functional/api/test_download_content.py::DownloadContentTestCase::test_all PASSED                                                                  [ 87%]
pulp_python/tests/functional/api/test_publish.py::PublishAnyRepoVersionTestCase::test_all PASSED                                                                     [ 90%]
pulp_python/tests/functional/api/test_sync.py::SyncPythonRepoTestCase::test_sync PASSED                                                                              [ 93%]
pulp_python/tests/functional/api/test_sync.py::SyncChangeRepoVersionTestCase::test_all PASSED                                                                        [ 96%]
pulp_python/tests/functional/api/test_sync.py::MultiResourceLockingTestCase::test_all PASSED                                                                         [100%]
```

**Comment by bmbouter** [comment]
I did a code read through and it all looks sane.

**Comment by bmbouter** [comment]
I ran a double-sync on with some basic python classifiers and I downloaded the expected 20 packages on the first sync and 0 packages on the second one. Both completed successfully.

**Comment by dralley** [comment]
Between the smash tests, @CodeHeeler and @bmbouter , I'm confident in this.  Let's merge!

**Pull request merged**
