### PR TITLE
updated sync.sh, publication.sh and distribution.sh scripts

### PR DESCRIPTION
**Pull request by eorochena**
[noissue]

### CODE REVIEW

**Comment by eorochena** [comment]
This pull request is to address https://pulp.plan.io/issues/6918 but for some reason travis keeps failing even with the [noissue] label I will try to do the suggested changes 

with git add, commit --amend and push

Thanks

**Comment by dralley** [comment]
The reason its unhappy is that there isn't a changelog entry, create a file called ```CHANGES/6918.doc``` and write your short description there. Then Travis should pass.

**Comment by dralley** [comment]
Also, the reason adding ```[noissue]``` didn't work is because it's not in the commit message, just in the github description, and it needs to be in the commit message to be found in the automation.  But since there's an issue this is resolving, the appropriate thing is to add a changelog entry.

**Comment by eorochena** [comment]
@dralley Thanks for the advise, all checks now passed.

**Pull request merged**
