### PR TITLE
Adjusting documentation for the package_names config key

### PR DESCRIPTION
**Pull request by ipanova**
closes#1131
https://pulp.plan.io/issues/1131

### CODE REVIEW

**Comment by ipanova** [comment]
ok test

**Comment by asmacdo** [comment]
LGTM, whats up with Travis?

**Comment by ipanova** [comment]
ok test

**Comment by dkliban** [comment]
@ipanova You should just go ahead and merge. Randy fixed the problem, but it was done on master branch. Since this is just a documentation update, go ahead and merge.

**Comment by rbarlow** [comment]
Since this is a docs fix, it actually makes the most sense to merge it to 1.0-release instead of 1.0-dev. We probably won't release another 1.0.z so 1.0-dev probably won't ever go anywhere.

**Pull request closed without merging**
