### PR TITLE
Rename .rst

### PR DESCRIPTION
**Pull request by ryanhiebert**
It's already an rST file, so it's just changing the extension.

### CODE REVIEW

**Comment by ryanhiebert** [comment]
The build doesn't pass, but any fix to make it pass would not be related to this change.

**Comment by beav** [comment]
@ryanhiebert Thanks for your patch! I just merged #38 which should fix this test. Can you rebase and update the PR?

**Comment by ryanhiebert** [comment]
done.

**Comment by beav** [comment]
LGTM, merging patch.

Thanks again! :sunglasses:

**Pull request merged**
