### PR TITLE
Set `https_proxy` proxy setting

### PR DESCRIPTION
**Pull request by keilr**
fixes: #433

### CODE REVIEW

**Comment by gerrod3** [comment]
@keilr Thanks for the PR. To get it to pass the CI can you amend your commit message to include on the second line `fixes: #433`

**Review by dralley — APPROVED** [review]

**Comment by dralley** [comment]
Fix the CI as @gerrod3 mentioned, otherwise LGTM

**Comment by keilr** [comment]
> @keilr Thanks for the PR. To get it to pass the CI can you amend your commit message to include on the second line `fixes: #433`

done

**Comment by keilr** [comment]
@gerrod3 please back-port this fix to 3.5 if possible

**Comment by gerrod3** [comment]
> @gerrod3 please back-port this fix to 3.5 if possible

Here you go: https://pypi.org/project/pulp-python/3.5.2/

**Pull request merged**
